version: '3'

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    restart: always
    volumes:
        - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources/
        - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards/
        - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
