{
 "title": "Dashboard Produção",
 "description": "Desempenho da Produção",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Tarefas Previstas",
   "type": "stat",
   "description": "Tarefas previstas e bloqueadas",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(p.id) as 'Tarefas Em Andamento'\nfrom project_objects po\nleft join projects p ON (po.project_id = p.id )\n\nwhere po.type = 'Task' \nand (po.label_id = 17 )\nand po.state = 3 \nand po.completed_on is NULL \nand p.completed_on is NULL ;\n"
    }
   ]
  },
  {
   "title": "Tarefas em Aberto NAO Atribuídas",
   "type": "stat",
   "description": "Status = NOVO e \nStatus = REABERTO ",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "-- Tarefas Em aberto\nSELECT count(p.id) as 'Tarefas Em Aberto'\nfrom project_objects po\nleft join projects p ON (po.project_id = p.id )\nwhere po.type = 'Task' \nand (po.label_id = 1 OR po.label_id = 10 )\nand po.state = 3 \nand po.completed_on is NULL\nand p.completed_on is NULL\nand po.assignee_id is NULL;"
    }
   ]
  },
  {
   "title": "Tarefas em Aberto Atribuídas",
   "type": "stat",
   "description": "Status = NOVO e \nStatus = REABERTO ",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "-- Tarefas Em aberto\nSELECT count(p.id) as 'Tarefas Em Aberto'\nfrom project_objects po\nleft join projects p ON (po.project_id = p.id )\nwhere po.type = 'Task' \nand (po.label_id = 1 OR po.label_id = 10 )\nand po.state = 3 \nand po.completed_on is NULL\nand p.completed_on is NULL\nand po.assignee_id is NOT NULL;"
    }
   ]
  },
  {
   "title": "Tarefas em Andamento",
   "type": "stat",
   "description": "Tarefas com status ANDAMENTO",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(p.id) as 'Tarefas Em Andamento'\nfrom project_objects po\nleft join projects p ON (po.project_id = p.id )\n\nwhere po.type = 'Task' \nand po.label_id = 8 \nand po.state = 3 \nand po.completed_on is NULL \nand p.completed_on is NULL ;\n"
    }
   ]
  },
  {
   "title": "Tarefas em Revisão",
   "type": "stat",
   "description": "Tarefas com status REVISAO",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(p.id) as 'Tarefas Em Andamento'\nfrom project_objects po\nleft join projects p ON (po.project_id = p.id )\n\nwhere po.type = 'Task' \nand po.label_id = 18 \nand po.state = 3 \nand po.completed_on is NULL \nand p.completed_on is NULL ;\n"
    }
   ]
  },
  {
   "title": "Tarefas Concluídas",
   "type": "stat",
   "description": "Tarefas com status CONCLUIDO",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(p.id) as 'Tarefas Em Andamento'\nfrom project_objects po\nleft join projects p ON (po.project_id = p.id )\n\nwhere po.type = 'Task' \nand po.label_id = 9 \nand po.state = 3 \nand po.completed_on is NULL \nand p.completed_on is NULL ;\n"
    }
   ]
  },
  {
   "title": "Tarefas Bloqueadas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(p.id) as 'Tarefas Em Andamento'\nfrom project_objects po\nleft join projects p ON (po.project_id = p.id )\n\nwhere po.type = 'Task' \nand (po.label_id = 7 )\nand po.state = 3 \nand po.completed_on is NULL \nand p.completed_on is NULL ;\n"
    }
   ]
  },
  {
   "title": "Faturadas",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \n\tuser_name AS 'Colaborador' , \n\tSUM(value) AS 'Horas' \nFROM  `time_records` \nWHERE $__timeFilter(record_date)\nAND state = 3 AND (billable_status = 1  OR billable_status = 2 OR billable_status = 3) \nGROUP BY user_name;"
    }
   ]
  },
  {
   "title": "Faturadas/Não Faturadas",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \n\tuser_name AS 'Colaborador' , \n\tSUM(value) AS 'Horas' \nFROM  `time_records` \nWHERE $__timeFilter(record_date)\nAND state = 3 AND (billable_status = 0  OR billable_status = 1  OR billable_status = 2 OR billable_status = 3) \nGROUP BY user_name;"
    }
   ]
  },
  {
   "title": "Faturadas",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \n\tc.name AS Cliente , \n\tSUM(value) AS 'Horas' \nFROM  `time_records` tr\nLEFT JOIN project_objects po ON (po.id = tr.parent_id)\nLEFT JOIN projects p ON (p.id = po.project_id)\nLEFT JOIN companies c ON (c.id = p.company_id)\n\nWHERE $__timeFilter(record_date)\nAND tr.state = 3\nAND ( tr.billable_status = 1  OR tr.billable_status = 2 OR tr.billable_status = 3) \nGROUP BY c.id;"
    }
   ]
  },
  {
   "title": "Faturadas/Não Faturadas",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \n\tc.name AS Cliente , \n\tSUM(value) AS 'Horas' \nFROM  `time_records` tr\nLEFT JOIN project_objects po ON (po.id = tr.parent_id)\nLEFT JOIN projects p ON (p.id = po.project_id)\nLEFT JOIN companies c ON (c.id = p.company_id)\n\nWHERE $__timeFilter(record_date)\nAND tr.state = 3\nAND (tr.billable_status = 0  OR  tr.billable_status = 1  OR tr.billable_status = 2 OR tr.billable_status = 3) \nGROUP BY c.id;"
    }
   ]
  },
  {
   "title": "Horas Faturadas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n\tSUM(value) AS 'Horas' \nFROM  `time_records` \nWHERE $__timeFilter(record_date)\nAND state = 3 AND (billable_status = 1  OR billable_status = 2 OR billable_status = 3) ;"
    }
   ]
  }
 ]
}