{
 "title": "Dashboard Produção Publico dothCom",
 "description": "Desempenho da Produção",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Produção", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Atividades Recentes",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  created_on as 'time',\n  created_by_name AS metric,\n  action\nFROM activity_logs\nWHERE\n  id > 0\nORDER BY created_on desc limit 10;"
    }
   ]
  },
  {
   "title": "Previstas",
   "type": "stat",
   "description": "Tarefas previstas e bloqueadas",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(p.id) as 'Tarefas Em Andamento'\nfrom project_objects po\nleft join projects p ON (po.project_id = p.id )\n\nwhere po.type = 'Task' \nand (po.label_id = 17 )\nand po.state = 3 \nand po.completed_on is NULL \nand p.completed_on is NULL ;\n"
    }
   ]
  },
  {
   "title": "Em Aberto (Não Atribuídas)",
   "type": "stat",
   "description": "Status = NOVO e \nStatus = REABERTO ",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "-- Tarefas Em aberto\nSELECT count(p.id) as 'Tarefas Em Aberto'\nfrom project_objects po\nleft join projects p ON (po.project_id = p.id )\nwhere po.type = 'Task' \nand (po.label_id = 1 OR po.label_id = 10 )\nand po.state = 3 \nand po.completed_on is NULL\nand p.completed_on is NULL\nand po.assignee_id is NULL;"
    }
   ]
  },
  {
   "title": "Em Aberto (Atribuídas)",
   "type": "stat",
   "description": "Status = NOVO e \nStatus = REABERTO ",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "-- Tarefas Em aberto\nSELECT count(p.id) as 'Tarefas Em Aberto'\nfrom project_objects po\nleft join projects p ON (po.project_id = p.id )\nwhere po.type = 'Task' \nand (po.label_id = 1 OR po.label_id = 10 )\nand po.state = 3 \nand po.completed_on is NULL\nand p.completed_on is NULL\nand po.assignee_id is NOT NULL;"
    }
   ]
  },
  {
   "title": "Em Andamento",
   "type": "stat",
   "description": "Tarefas com status ANDAMENTO",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(p.id) as 'Tarefas Em Andamento'\nfrom project_objects po\nleft join projects p ON (po.project_id = p.id )\n\nwhere po.type = 'Task' \nand po.label_id = 8 \nand po.state = 3 \nand po.completed_on is NULL \nand p.completed_on is NULL ;\n"
    }
   ]
  },
  {
   "title": "Em Revisão",
   "type": "stat",
   "description": "Tarefas com status REVISAO",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(p.id) as 'Tarefas Em Andamento'\nfrom project_objects po\nleft join projects p ON (po.project_id = p.id )\n\nwhere po.type = 'Task' \nand po.label_id = 18 \nand po.state = 3 \nand po.completed_on is NULL \nand p.completed_on is NULL ;\n"
    }
   ]
  },
  {
   "title": "Concluídas",
   "type": "stat",
   "description": "Tarefas com status CONCLUIDO",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(p.id) as 'Tarefas Em Andamento'\nfrom project_objects po\nleft join projects p ON (po.project_id = p.id )\n\nwhere po.type = 'Task' \nand po.label_id = 9 \nand po.state = 3 \nand po.completed_on is NULL \nand p.completed_on is NULL ;\n"
    }
   ]
  },
  {
   "title": "Bloqueadas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(p.id) as 'Tarefas Em Andamento'\nfrom project_objects po\nleft join projects p ON (po.project_id = p.id )\n\nwhere po.type = 'Task' \nand (po.label_id = 7 )\nand po.state = 3 \nand po.completed_on is NULL \nand p.completed_on is NULL ;\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 17, "x": 7, "y": 8 },
   "options": {
    "content": "\n<h1 style=\"font-size:40px; text-align:center\"> \nRegistros do Período Selecionado </h1>\n\n\n\n\n"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  accessed_on AS \"time\",\n  id\nFROM access_logs\nWHERE\n  $__timeFilter(accessed_on)\nORDER BY accessed_on"
    }
   ]
  },
  {
   "title": "Distribuição de Tarefas",
   "type": "stat",
   "description": "Tarefas alocadas para os colaboradores",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "-- Tarefas Em aberto ATRIBUIDAS\nSELECT u.first_name AS 'Colaborador' , count(po.id) as 'Tarefas'\nfrom project_objects po\nleft join projects p ON (po.project_id = p.id )\nleft join users u ON (u.id = po.assignee_id )\nWHERE  po.type = 'Task' \nand (po.label_id = 1 OR po.label_id = 8 OR po.label_id = 10 OR po.label_id = 18)\nand po.state = 3 \nand po.completed_on is NULL\nand p.completed_on is NULL\nand po.assignee_id is NOT NULL\nGROUP by u.id \n;"
    }
   ]
  },
  {
   "title": "Faturadas 😀",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 2, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(value) from (\nSELECT value FROM `time_records` WHERE $__timeFilter(record_date) AND state = 3 AND parent_type = \"Task\" AND (billable_status = 1  OR billable_status = 2 OR billable_status = 3) union all\nSELECT value/130 FROM `expenses` WHERE $__timeFilter(record_date) AND state = 3  AND (billable_status = 1  OR billable_status = 2 OR billable_status = 3) \n    )\nx"
    }
   ]
  },
  {
   "title": "Faturadas 😀",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 9, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "projetos",
     "rawSql": "SELECT \n\tc.name AS 'Cliente' , \n\t(value) AS 'Faturadas' \nFROM  `time_records` tr\nLEFT JOIN project_objects po ON (po.id = tr.parent_id)\nLEFT JOIN projects p ON (p.id = po.project_id)\nLEFT JOIN companies c ON (c.id = p.company_id)\n\nWHERE $__timeFilter(record_date)\nAND tr.state = 3\nAND parent_type = \"Task\"\nAND ( tr.billable_status = 1  ) \nGROUP BY c.id;"
    }
   ]
  },
  {
   "title": "Não Faturadas 🙁",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 2, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\nSELECT SUM(value) FROM `time_records` WHERE $__timeFilter(record_date) \nAND state = 3 AND parent_type = \"Task\" AND (billable_status = 0  ) \n\n"
    }
   ]
  },
  {
   "title": "Não Faturadas 🙁",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 7, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "projetos",
     "rawSql": "\nSELECT \n\tc.name AS Cliente , \n\tSUM(value) AS 'Ñ Faturadas' \nFROM  `time_records` tr\nLEFT JOIN project_objects po ON (po.id = tr.parent_id)\nLEFT JOIN projects p ON (p.id = po.project_id)\nLEFT JOIN companies c ON (c.id = p.company_id)\n\nWHERE $__timeFilter(record_date)\nAND tr.state = 3\nAND parent_type = \"Task\"\nAND ( tr.billable_status = 0   OR tr.billable_status = 2 OR tr.billable_status = 3) \nGROUP BY c.id order by `Ñ Faturadas` DESC  ;"
    }
   ]
  },
  {
   "title": "Em andamento",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Tarefas Em aberto ATRIBUIDAS\nSELECT u.first_name as 'Colaborador' , count(po.id)\nfrom project_objects po\nleft join projects p ON (po.project_id = p.id )\nleft join users u ON (u.id = po.assignee_id )\nWHERE  po.type = 'Task' \nand (po.label_id = 8)\nand po.state = 3 \nand po.completed_on is NULL\nand p.completed_on is NULL\nand po.assignee_id is NOT NULL\nGROUP by u.id \n;"
    }
   ]
  }
 ]
}